version: "3.8"
services:
    mysqldb:
        image: mysql:8.0
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        volumes:
            - db:/var/lib/mysql
    volcano-camping-api:
        depends_on:
            - mysqldb
        build: ./
        env_file: ./.env
        ports:
            - "8080:8081"
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
                "spring.datasource.username" : "$MYSQLDB_USER",
                "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
                "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
                "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update",
                "server.port" : "8081"
              }'
        volumes:
            - .m2:/root/.m2
        restart: on-failure
volumes:
    db: